### ISSUE TITLE
Can AI2Thor turn off the visual interface for acceleration during training RL

### ISSUE THREAD

**Issue by snow2white** [mattdeitke/mattdeitke#1]
Hi, I am using AI2Thor for RL research recently. I want to use AI2Thor to realize an indoor navigation function, but the visual interface of RL research greatly reduces the speed of research. I hope to close the screen and still return the data information of agent

**Comment by mattdeitke** [comment]
Hi @renew1-ss,

Are you trying to not render any images, and just use the metadata? If so, that will speed up training.

Alternatively, if you're trying to still use the images (i.e., `event.frame`), but just close the Unity window that pops up, closing the window that pops up will not speed up training that much in most cases. However, in some cases (i.e., running on a headless machine), it speeds up training a lot, and will be publicly supported soon! Expect a blog post on it in the next week or so.

(Also note: If you have AI2-THOR questions, asking them on [allenai/ai2thor](https://github.com/allenai/ai2thor/) is both the fastest way to get a response, and the easiest way for us to index all of them.)

**Comment by snow2white** [comment]
> Hi @renew1-ss,
> 
> Are you trying to not render any images, and just use the metadata? If so, that will speed up training.
> 
> Alternatively, if you're trying to still use the images (i.e., `event.frame`), but just close the Unity window that pops up, closing the window that pops up will not speed up training that much in most cases. However, in some cases (i.e., running on a headless machine), it speeds up training a lot, and will be publicly supported soon! Expect a blog post on it in the next week or so.
> 
> (Also note: If you have AI2-THOR questions, asking them on [allenai/ai2thor](https://github.com/allenai/ai2thor/) is both the fastest way to get a response, and the easiest way for us to index all of them.)
you say"Are you trying to not render any images, and just use the metadata"

yes, I just want to speed up the training, but I don't know how to write the code, Can you give me a rough idea of how to write it

thank you

**Comment by renew1-ss** [comment]
Are you trying to not render any images, and just use the metadata


yes, I just want to speed up the training, but I don't know how to write the code

**Comment by renew1-ss** [comment]
> > Hi @renew1-ss,
> > Are you trying to not render any images, and just use the metadata? If so, that will speed up training.
> > Alternatively, if you're trying to still use the images (i.e., `event.frame`), but just close the Unity window that pops up, closing the window that pops up will not speed up training that much in most cases. However, in some cases (i.e., running on a headless machine), it speeds up training a lot, and will be publicly supported soon! Expect a blog post on it in the next week or so.
> > (Also note: If you have AI2-THOR questions, asking them on [allenai/ai2thor](https://github.com/allenai/ai2thor/) is both the fastest way to get a response, and the easiest way for us to index all of them.)


you say"Are you trying to not render any images, and just use the metadata"

yes, I just want to speed up the training, but I don't know how to write the code
